# Generated by Django 4.2.20 on 2026-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.TextField(default="[]"),
        ),
    ]
