# Generated by Django 4.2.17 on 2026-02-07 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["expiry_date"]},
        ),
        migrations.AddField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="quantity_reserved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("shipped", "Shipped"),
                    ("expired", "Expired"),
                ],
                default="available",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="storage_location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="api.batch",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("received", "Stock Received"),
                            ("reserved", "Reserved for Order"),
                            ("shipped", "Shipped"),
                            ("returned", "Returned"),
                            ("expired", "Expired"),
                            ("adjusted", "Manual Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_changed", models.IntegerField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.batch",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="api.product",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
