# Generated by Django 4.2.17 on 2026-02-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_batch_options_batch_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="batch",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
