# Generated by Django 4.2.17 on 2026-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_batch_image_alt_batch_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="batches/"),
        ),
    ]
