# Generated by Django 4.2.28 on 2026-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_batch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True, default="/placeholder.svg", max_length=255
            ),
        ),
    ]
