# Generated by Django 4.2.28 on 2026-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_product_image_alter_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="special_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
